"""create source_events table

Revision ID: 471d38ead9e5
Revises: 8ffb0bfa1f08
Create Date: 2026-08-19 17:51:33.775644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '471d38ead9e5'
down_revision: Union[str, Sequence[str], None] = '8ffb0bfa1f08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_events_id'), table_name='source_events')
    op.drop_index(op.f('ix_source_events_source_external_id'), table_name='source_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_source_events_source_external_id'), 'source_events', ['source', 'external_id'], unique=False)
    op.create_index(op.f('ix_source_events_id'), 'source_events', ['id'], unique=False)
    # ### end Alembic commands ###
