"""create source_events table

Revision ID: 8ffb0bfa1f08
Revises: 0d706e9ea4f5
Create Date: 2026-08-19 17:03:29.908782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ffb0bfa1f08'
down_revision: Union[str, Sequence[str], None] = '0d706e9ea4f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('course', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_source_external_id')
    )
    op.create_index(op.f('ix_source_events_id'), 'source_events', ['id'], unique=False)
    op.create_index(op.f('ix_source_events_source'), 'source_events', ['source'], unique=False)
    op.create_index('ix_source_events_source_external_id', 'source_events', ['source', 'external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_source_events_source_external_id', table_name='source_events')
    op.drop_index(op.f('ix_source_events_source'), table_name='source_events')
    op.drop_index(op.f('ix_source_events_id'), table_name='source_events')
    op.drop_table('source_events')
    # ### end Alembic commands ###
