"""create source_events table

Revision ID: 9176502c3282
Revises: a99e5f1d6708
Create Date: 2026-08-21 06:19:54.045994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9176502c3282'
down_revision: Union[str, Sequence[str], None] = 'a99e5f1d6708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_source_events_external_id'), 'source_events', ['external_id'], unique=False)
    op.create_index(op.f('ix_source_events_id'), 'source_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_events_id'), table_name='source_events')
    op.drop_index(op.f('ix_source_events_external_id'), table_name='source_events')
    # ### end Alembic commands ###
