"""add default created_at to source_events

Revision ID: c5b2882fdf02
Revises: 9176502c3282
Create Date: 2026-08-21 10:47:33.475355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5b2882fdf02'
down_revision: Union[str, Sequence[str], None] = '9176502c3282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_events_id'), table_name='source_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_source_events_id'), 'source_events', ['id'], unique=False)
    # ### end Alembic commands ###
